
```{r}
data <- read.csv("C:/Users/Shombit Roy/OneDrive/Desktop/Reserach data/Center_for_Medicare___Medicaid_Services__CMS____Medicare_Claims_data_20240208 (1).csv")

library(dplyr)
```

```{r}
head(data)
str(data) 

```

```{r}
library(dplyr)

demographic_trends <- data %>%
  group_by(YearStart, Break_Out_Category) %>%
  summarise(RecordCount = n(), .groups = 'drop')

demographic_trends
```

```{r}
library(ggplot2)

ggplot(demographic_trends, aes(x = YearStart, y = RecordCount, color = Break_Out_Category)) +
  geom_line() +
  theme_minimal() +
  labs(title = "Trends in Medicare Claims by Demographic Category", x = "Year", y = "Record Count")


```
# After the time series analysis and plotting using ggplot2, it's shown that the factor race plays a bigger role compared to the other factors in terms of heart disease. For future EDA, it's important to focus on the underlying reasoning for this (further filtering and selecting in smaller geographical units). 
